name: agrivision
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  lucide_icons: ^0.257.0
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4

  # State Management
  provider: ^6.1.2
  shared_preferences: ^2.0.8

  # Image & File Handling
  image_picker: ^1.0.4
  permission_handler: ^11.0.1

  # URL launcher
  url_launcher: ^6.3.1

  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0

  # eSewa Flutter SDK (local path)
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk

  # Webview for eSewa payment
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.7.0
  webview_flutter_platform_interface: ^2.1.2

  http: ^0.13.6
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/agricultures_logo.png
    - assets/background.jpg
    - assets/agrivision_logo.png
    - assets/Arbind.jpg
    - assets/dev.jpg
    - assets/nandlal.jpg
    - assets/pradip.jpg
    - assets/prince.jpg
    - assets/raju.jpg
    - assets/rajalal.jpg
    - assets/rakesh.jpg
    - assets/shailendra.jpg
    - assets/apple.jpg
    - assets/banana.jpg
    - assets/spinach.jpg
    - assets/carrot.jpg
    - assets/potato.jpg
    - assets/tomato.jpg
    - assets/barley.jpg
    - assets/gingerherbs.jpg
    - assets/lemonbalm.jpg
    - assets/maizecrops.jpg
    - assets/millet.png
    - assets/onioncrops.jpg
    - assets/rice.jpg
    - assets/ricecrops.jpg
    - assets/sugarcanecrops.jpg
    - assets/sunflowerherbs.jpg
    - assets/turnipherbs.jpg
    - assets/wheatcrops.jpg
    - assets/buffalomilk.jpg
    - assets/cheese.jpg
    - assets/cream.jpg
    - assets/curd.jpg
    - assets/grapes.jpg
    - assets/guava.jpg
    - assets/lichi.jpg
    - assets/mango.jpg
    - assets/milk.jpg
    - assets/orange.jpg
    - assets/pineapple.jpg

